# Generated by Django 5.0.6 on 2024-06-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
